<?php

namespace AdminBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * BaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseRepository extends \Doctrine\ORM\EntityRepository
{
    protected const PAGE_SIZE = 25;

    public function getPage($page, $search = null)
    {
        $qb = $this->createQueryBuilder('e');

        if ($search !== null && $search !== '') {
            $fulltextFields = array_map(
                function ($columnName) {
                    return 'e.' . $this->getClassMetaData()->getFieldName($columnName);
                },
                $this->getClassMetaData()->table['indexes']['fulltext']['columns']
            );

            $qb->add('where', 'MATCH(' . implode($fulltextFields, ',') . ') AGAINST(:search) > 0')
                ->setParameter('search', $search);
        }

        $query = $qb->getQuery()
            ->setFirstResult(self::PAGE_SIZE * ($page - 1))
            ->setMaxResults(self::PAGE_SIZE);

        $paginator = new Paginator($query);

        $pageCount = ceil(count($paginator) / self::PAGE_SIZE);

        return [
            'list' => $paginator,
            'pageCount' => $pageCount
        ];
    }
}
